### ISSUE TITLE
Adicionar exercícios e desafios

### ISSUE THREAD

**Issue by ftonato** [ftonato/meetup#1]
- [X] Encontro 01 - Exercícios
- [X] Encontro 01 - Desafio
- [x] Encontro 02 - Exercícios
- [X] Encontro 02 - Desafio
- [ ] Encontro 03 - Exercícios
- [ ] Encontro 03 - Desafio
- [ ] Encontro 04 - Exercícios
- [ ] Encontro 04 - Desafio

**Comment by GBeckerRS** [comment]
Um exercício clássico de programação, é a boa e velha calculadora =)
Com operações de soma, subtração, divisão, multiplicação, módulo....

**Comment by ftonato** [comment]
@GBeckerRS Adicionarei  :+1:

**Comment by ftonato** [comment]
O assunto dessa _issue_ passou a ser tratado na _issue_ #2
